# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registr.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registr(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 395)
        Form.setStyleSheet("background-color: rgb(201, 250, 255);\n"
"")
        self.client_label = QtWidgets.QLabel(Form)
        self.client_label.setGeometry(QtCore.QRect(150, 30, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.client_label.setFont(font)
        self.client_label.setObjectName("client_label")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 160, 331, 107))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_Imia_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.lineEdit_Imia_2.setFont(font)
        self.lineEdit_Imia_2.setStyleSheet("background-color: rgb(242, 255, 253);")
        self.lineEdit_Imia_2.setObjectName("lineEdit_Imia_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Imia_2)
        self.label_imia = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_imia.setFont(font)
        self.label_imia.setObjectName("label_imia")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_imia)
        self.lineEdit_Imia_3 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.lineEdit_Imia_3.setFont(font)
        self.lineEdit_Imia_3.setStyleSheet("background-color: rgb(242, 255, 253);")
        self.lineEdit_Imia_3.setObjectName("lineEdit_Imia_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Imia_3)
        self.label_imia_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_imia_2.setFont(font)
        self.label_imia_2.setObjectName("label_imia_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_imia_2)
        self.pushButton_delete = QtWidgets.QPushButton(Form)
        self.pushButton_delete.setGeometry(QtCore.QRect(170, 330, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("background-color: rgb(128, 200, 255);\n"
"")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_delete_2 = QtWidgets.QPushButton(Form)
        self.pushButton_delete_2.setGeometry(QtCore.QRect(100, 280, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.pushButton_delete_2.setFont(font)
        self.pushButton_delete_2.setStyleSheet("background-color: rgb(128, 200, 255);\n"
"")
        self.pushButton_delete_2.setObjectName("pushButton_delete_2")
        self.label_pustaia = QtWidgets.QLabel(Form)
        self.label_pustaia.setGeometry(QtCore.QRect(0, 100, 511, 39))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_pustaia.setFont(font)
        self.label_pustaia.setText("")
        self.label_pustaia.setObjectName("label_pustaia")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.client_label.setText(_translate("Form", "Регистрация"))
        self.label_imia.setText(_translate("Form", "Логин"))
        self.label_imia_2.setText(_translate("Form", "Пароль"))
        self.pushButton_delete.setText(_translate("Form", "Вход"))
        self.pushButton_delete_2.setText(_translate("Form", "Зарегистрироваться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_registr()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
